name: Build, Test, and Publish Wheels

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

##########################################
# 1) Ubuntu builds for all desired versions
##########################################
jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8.16", "3.9.16", "3.10.12", "3.11.6", "3.12.0"]
        architecture: ["x64"]
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Inject short Python version
        run: echo "PYTHON_VERSION_SHORT=${{ matrix.python-version }}" | sed -E 's/\.([0-9]+)$//' | sed 's/\.//g' >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip twine cibuildwheel==2.22.0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build wheels
        run: cibuildwheel --output-dir dist/
        env:
          CIBW_SKIP: "pp* musllinux_1* musllinux* *-win32 *-ppc64le *-s390x *i686"
          CIBW_BUILD: "cp${{ env.PYTHON_VERSION_SHORT }}-*"
          CIBW_BEFORE_BUILD: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y &&
            export PATH=$HOME/.cargo/bin:$PATH &&
            pip install maturin
          CIBW_ENVIRONMENT: PATH=$HOME/.cargo/bin:$PATH

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-ubuntu-{{ matrix.python-version }}
          path: dist/*.whl

  ########################################################
  # 2) Older Python on Intel macOS (3.8, 3.9, 3.10) - x64
  ########################################################
  build-macos-older:
    name: Build older Python on Intel macOS
    # Pin to an Intel-based image (macos-13).
    # (Note: GitHub could eventually switch it to Apple Silicon, but for now it should be Intel.)
    runs-on: macos-13
    strategy:
      matrix:
        python-version: ["3.8.16", "3.9.16", "3.10.12"]
        # We only do x64 here, so no architecture matrix needed
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install missing dependencies
        run: |
          brew install gettext
          echo "DYLD_LIBRARY_PATH=$(brew --prefix gettext)/lib" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64 # specifically x64 on Intel

      - name: Install dependencies
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip maturin twine

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Wheels
        run: maturin build --release

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-older-{{ matrix.python-version }}
          path: target/wheels/*.whl

  ################################################
  # 3) Newer Python on macOS-latest (3.11, 3.12)
  ################################################
  build-macos-newer:
    name: Build newer Python on macOS-latest
    runs-on: macos-latest
    strategy:
      matrix:
        # Only build 3.11 and 3.12 on macOS-latest
        python-version: ["3.11.6", "3.12.0"]
        # Decide if you want just arm64, or arm64 + x64.
        # The snippet below uses only arm64 for a native Apple Silicon build.
        architecture: ["arm64", "x64"]
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install missing dependencies
        run: |
          brew install gettext
          echo "DYLD_LIBRARY_PATH=$(brew --prefix gettext)/lib" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip maturin twine

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Wheels
        run: maturin build --release

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-newer-{{ matrix.python-version }}
          path: target/wheels/*.whl

  ##########################################
  # 4) Publish job that combines all wheels
  ##########################################
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-macos-older, build-macos-newer]
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v3
        with:
          path: wheels

      - name: Flatten wheel directory structure
        run: |
          mkdir -p ./all-wheels
          find ./wheels -name '*.whl' -exec mv {} ./all-wheels \;

      - name: Publish to PyPI
        run: |
          python -m pip install --upgrade pip twine
          twine upload ./all-wheels/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
